#!/bin/sh /etc/rc.common

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1
SERVICE_PID_FILE=/var/run/adblock.pid

start() {
	/usr/bin/adblock start
	/usr/bin/adblock daemon&
}

stop() {
	/usr/bin/adblock stop
}
